### ISSUE TITLE
Blank page after publishing - error enclosed

### ISSUE THREAD

**Issue by joelvarty** [agility/Agility.AspNetCore#10]
After a publish, this error is happening.  Subsequent requests go through ok after that.

*** Error    *** RD0003FF8360EF *** 2019-11-04 15:07:20
Request Details:
URL: https://agilitycms.com/error/500
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/13.0.3 Safari/605.1.15
Host Address: 184.94.118.194
Username: 
System.NullReferenceException: Object reference not set to an instance of an object.
   at Agility.Web.Caching.AgilityResponseCacheMiddleware.IsCacheable(HttpContext context)
   at Agility.Web.Caching.AgilityResponseCacheMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.Invoke(HttpContext context)

**Comment by jamesvidler** [comment]
Closed due to inactivity
